応用課題15 model spec作成
shinsaku-ta/sample_app_for_rspec pull request #2
Opened 2019-11-02 13:00 UTC by inasakunovel

## 概要

taskモデルのバリデーションに関するテストを作成

## 確認方法

バリデーションありテスト
<img width="703" alt="スクリーンショット 2019-11-02 21 44 52" src="https://user-images.githubusercontent.com/53027254/68071209-a1656800-fdbb-11e9-8ff9-c27da5f67823.png">

バリデーション削除しテスト
<img width="1311" alt="スクリーンショット 2019-11-02 21 50 04" src="https://user-images.githubusercontent.com/53027254/68071211-a32f2b80-fdbb-11e9-82fa-369a341ed06c.png">
バリデーション編集しテスト
<img width="581" alt="スクリーンショット 2019-11-02 21 58 47" src="https://user-images.githubusercontent.com/53027254/68071255-06b95900-fdbc-11e9-9301-a9fb8651a8da.png">

## 影響範囲

## チェックリスト

- [ ]  modelのvalidationを編集・削除した場合に、テストが失敗することを確認
- [ ] テストデータの作成には FactoryBot と let を使う
- [ ] describe, context it を使い分ける
- [ ] .rspec ファイルに --format documentation を追記

## コメント
よろしくお願いします！

2019-11-05 03:18 UTC, yuji91 commented on spec/factories/users.rb
> +    email                  { "test@gamil.com" }
`@gamil.com` というドメインが存在していた場合、メール送信テストなど情報漏洩のリスクがあるので、
テストデータのメールアドレスは下記の存在しないドメインを使用してください。

https://blog.ko31.com/201304/sample-domain-example/

2019-11-05 03:19 UTC, yuji91 commented on spec/models/task_spec.rb
> +          expect(task).to_not be_valid
`task.errors` でバリデーションエラーメッセージも確認しておきましょう！

2019-11-05 03:44 UTC, yuji91 commented on spec/models/task_spec.rb
> +    describe 'タイトルのバリデーションテスト' do
contextにはテストケースの条件、itには確認対象を記載した方が良いですね。

また、確認対象のカラムが増えるごとに describeが増えるので、下記のような記載の方が良いかと思います！
```rb
describe 'バリデーション確認' do
  context 'タイトルが空の場合' do
     it 'バリデーションエラーが発生する' do
  context '入力値が正常な場合' do
     it 'バリデーションエラーが発生しない' do
```

2019-11-05 03:45 UTC, yuji91 commented on Gemfile
> +  gem 'factory_bot_rails'
同じgemを2つ追加していると思います！

2019-11-05 03:50 UTC, yuji91 requested changes
コメントしました！

2019-11-05 04:41 UTC, yuji91 commented on spec/factories/users.rb
> +    password               { "000000" }
`sequence(:email) { |n| "example-#{n}@example.com" }` のようにシーケンスを使うことで、UserのFactoryを複数回作成してもUniqueValidationで落ちなくなります。

2019-11-05 04:41 UTC, yuji91 commented on spec/models/task_spec.rb
> +    let(:user){ create :user }
taskのFactoryに `association :user` と記載することで userをletで定義する必要がなくなると思います！

2019-11-05 05:25 UTC, inasakunovel commented on spec/factories/users.rb
> +    email                  { "test@gamil.com" }
72c566f で実装しました。

2019-11-05 05:26 UTC, inasakunovel commented on spec/models/task_spec.rb
> +    describe 'タイトルのバリデーションテスト' do
a16187f　で実装しました。

2019-11-05 05:27 UTC, inasakunovel commented on Gemfile
> +  gem 'factory_bot_rails'
8b69e0b　で実装しました。

2019-11-05 05:28 UTC, inasakunovel commented on spec/models/task_spec.rb
> +          expect(task).to_not be_valid
a16187f　で実装しました。

2019-11-05 05:28 UTC, inasakunovel commented on spec/factories/users.rb
> +    password               { "000000" }
c183ab0　で実装しました。

2019-11-05 05:28 UTC, inasakunovel commented on spec/models/task_spec.rb
> +    let(:user){ create :user }
2ad945c　で実装しました。

2019-11-07 05:14 UTC, yuji91 commented on spec/factories/tasks.rb
> -
taskのFactoryを作成した時にそれ単体でテストデータが作成出来るよう、各attributeも定義してください。
`FactoryBot.create(:task)` でエラーなくデータが作成出来るようにして欲しいです。

2019-11-07 05:17 UTC, yuji91 commented on spec/models/task_spec.rb
> +        task.valid?
`be_valid` があるため `task.valid?` を記載しなくても `task.errors` が実行可能となります。
そのため `task.valid?` は不要です！

2019-11-07 05:22 UTC, yuji91 commented on spec/models/task_spec.rb
> +      end
共通化している訳ではないので、beforeに記載する必要がないと思います。
例ですが `FactoryBot.create(:task, title: 'unique_title')` 実行後に `duplicated_task = FactoryBot.build(:task, title: 'unique_title')` と記載する形式で良いかと思います。

2019-11-07 05:27 UTC, yuji91 commented on spec/models/task_spec.rb
> +        task.valid?
`task.valid?` が不要ですね

2019-11-07 05:31 UTC, yuji91 commented on spec/rails_helper.rb
> +  config.include FactoryBot::Syntax::Methods
この記述があれば `FactoryBot.create(:task)` などの部分は全て `create(:task)` で記載できます。

2019-11-07 05:31 UTC, yuji91 requested changes
コメントしました！

2019-11-07 06:26 UTC, inasakunovel commented on spec/rails_helper.rb
> +  config.include FactoryBot::Syntax::Methods
9a8e915 で実装しました。

2019-11-07 06:27 UTC, inasakunovel commented on spec/models/task_spec.rb
> +        task.valid?
6c19520　で実装しました。

2019-11-07 06:27 UTC, inasakunovel commented on spec/models/task_spec.rb
> +        task.valid?
6c19520　で実装しました。

2019-11-07 06:31 UTC, inasakunovel commented on spec/models/task_spec.rb
> +      end
47db2fc 84373e7　で実装しました。

2019-11-07 06:32 UTC, inasakunovel commented on spec/factories/tasks.rb
> -
0900df1　で実装しました。

2019-11-07 07:06 UTC, yuji91 commented on spec/models/task_spec.rb
> +    end
正常系のパターンは1ケースだけ作成すれば問題ないです！
attribute毎に作成すると、validationが増える毎にテストケースを余分に作成する必要が出てしまうので、
```
task = build(:task)
expect(task).to be_valid
```
で確認できれば良いです！

2019-11-07 07:13 UTC, inasakunovel commented on spec/models/task_spec.rb
> +    end
9bd56a3 で実装しました。

2019-11-07 07:14 UTC, yuji91 approved these changes
LGTMです！

2019-11-07 07:14 UTC, merged