課題16 system spec作成
shinsaku-ta/sample_app_for_rspec pull request #4
Opened 2019-11-07 06:50 UTC by inasakunovel

## 概要

タスクとユーザーに関するsystem specを作成し、テストケースを作成

## 確認方法

## 影響範囲

## チェックリスト

- [ ] ユーザーの新規作成、編集ができること
- [ ] ログインが成功すること
- [ ] ログインした状態でタスクの新規作成、編集、削除ができること
- [ ] マイページにユーザーが新規作成したタスクが表示
- [ ] メールアドレスが未入力時にユーザーの新規作成、編集が失敗
- [ ] 登録済メールアドレス使用時にユーザーの新規作成、編集が失敗
- [ ] フォーム未入力時にログインが失敗
- [ ] ログインしていないユーザーでタスクの新規作成、編集、マイページへの遷移ができないか
- [ ] 他のユーザーのユーザー編集、タスク編集ページへの遷移ができないか
- [ ] ログイン・ユーザー新規登録の成功時に対応するフラッシュメッセージが表示されること
- [ ] タスクの新規作成・編集・削除が成功した場合、対応するフラッシュメッセージと更新したデータが画面上に表示されていること
- [ ] ログイン・ユーザー新規登録の失敗時に対応するフラッシュメッセージが表示されること
- [ ] タスクの新規作成・編集が失敗した場合、対応するフラッシュメッセージと更新しようとしたデータが画面上に表示されていないこと
- [ ] 共通の確認観点として「処理後の遷移先のパスがどこか」を確認
- [ ] Controller毎にsystem specを作成し、確認対象の画面毎にdescribeを作成
- [ ] loginメソッドはmoduleを作成し、specファイル間で共通に呼び出せるようにする
- [ ] `--format documentation` を設定したテスト実行結果をPRに添付
- [ ] spec実行時に chrome/headless_chrome を切り替える設定を spec/support 以下に追加

## コメント
よろしくお願いします!

2019-11-07 09:27 UTC, yuji91 commented on spec/rails_helper.rb
> +end
`Dir[Rails.root.join('spec', 'support', '**', '*.rb')].each { |f| require f }` を記載しているため、別途 includeする必要はないと思います！

2019-11-07 09:28 UTC, yuji91 commented on spec/system/task_spec.rb
> +require 'support/login_macros'
`rails_helper.rb`で読み込んでいるので、ここでrequireする必要はないと思います！

2019-11-07 09:34 UTC, yuji91 commented on spec/system/users_spec.rb
> +          fill_in 'user_password_confirmation', with: 'password_after'
細かいですが `'password_changed'`や`'edited_password'`などの方が意図が伝わると思います。
beforeがある場合はafterを使って対比させて良いと思いますが、今回はbeforeがなくいきなりafterが出てくるので読み取りづらいです。

2019-11-07 10:10 UTC, yuji91 commented on spec/system/task_spec.rb
> +  end
```
contextにはテスト実行時の条件を記載して欲しいので、
  describe 'ログイン後' do
    describe 'タスクを作成' do
      context 'フォームの入力値が正常な場合' do
        it 'タスクの新規作成が成功する' 
      context 'フォームが未入力の場合' do
        it 'タスクの新規作成が失敗する' 
      context 'フォームに入力済のタイトルを' do
        it 'タスクの新規作成が失敗する' 
```

2019-11-07 10:14 UTC, inasakunovel commented on spec/system/task_spec.rb
> +require 'support/login_macros'
ec7e57b　で実装しました。

2019-11-07 10:15 UTC, inasakunovel commented on spec/rails_helper.rb
> +end
消すとエラーが出るため残したままにしました。

2019-11-07 10:15 UTC, inasakunovel commented on spec/system/users_spec.rb
> +          fill_in 'user_password_confirmation', with: 'password_after'
2e0c529　で実装しました。

2019-11-07 10:25 UTC, yuji91 commented on spec/system/users_spec.rb
> +        it "マイページへのアクセスが失敗する" do
細かいですがここだけダブルクォートになってます

2019-11-07 10:48 UTC, inasakunovel commented on spec/system/task_spec.rb
> +  end
cd2c6e1　で変更しました。

2019-11-07 10:48 UTC, inasakunovel commented on spec/system/users_spec.rb
> +        it "マイページへのアクセスが失敗する" do
768af94　で修正しました。

2019-11-07 11:02 UTC, yuji91 commented on Gemfile
> +  gem 'selenium-webdriver'
`selenium-webdriver`は不要だと思います！
https://everydayrails.com/2019/04/09/chromedriver-helper-webdrivers.html

2019-11-07 11:21 UTC, yuji91 commented on spec/rails_helper.rb
> +end
includeは必要でした。すみません！
`config.include FactoryBot::Syntax::Methods` と同様に、
`RSpec.configure do |config| end`で囲んで定義する必要はないのでそこだけ修正お願いします！

2019-11-07 11:31 UTC, inasakunovel commented on Gemfile
> +  gem 'selenium-webdriver'
f6eb20a　で修正しました。

2019-11-07 11:34 UTC, inasakunovel commented on spec/rails_helper.rb
> +end
9fd2b16 で修正しました。

2019-11-07 12:10 UTC, yuji91 commented on spec/system/users_spec.rb
> +        task
`have_content(task.title)`で遅延評価される際にtaskが作成されるので、最初に作成する必要はないと思います！

2019-11-07 12:14 UTC, yuji91 commented on Gemfile
> +end
`Gemfile.lock`に`selenium-webdriver`が残っていますが、bundle installしたときに該当箇所の記載は消えないかどうか確認をお願いしたいです！

2019-11-07 12:16 UTC, yuji91 requested changes
コメントしました！

2019-11-07 13:06 UTC, yuji91 commented on Gemfile
> +end
こちら`webdrives`で使用しているため、消えない挙動が正しいので問題ありませんでした。

2019-11-08 03:38 UTC, yuji91 commented on spec/system/users_spec.rb
> +        task
すみません。タスク読み込み前のページを確認しているので、現状の構成で大丈夫です！

2019-11-08 03:40 UTC, yuji91 commented on spec/system/task_spec.rb
> +        end
タスクの作成・編集時にフォーム未入力で失敗する場合の検証も追加して欲しいです！

2019-11-08 03:57 UTC, yuji91 approved these changes
LGTMです！

2019-11-08 03:59 UTC, merged